
export type Language = 'en' | 'da' | 'sv' | 'no' | 'fi' | 'es' | 'it' | 'fr' | 'de' | 'pt' | 'zh-hans' | 'zh-hant' | 'ja' | 'ko';

export const LANGUAGES: { code: Language; label: string; flag: string }[] = [
  { code: 'en', label: 'English', flag: '🇺🇸' },
  { code: 'da', label: 'Dansk', flag: '🇩🇰' },
  { code: 'sv', label: 'Svenska', flag: '🇸🇪' },
  { code: 'no', label: 'Norsk', flag: '🇳🇴' },
  { code: 'fi', label: 'Suomi', flag: '🇫🇮' },
  { code: 'es', label: 'Español', flag: '🇪🇸' },
  { code: 'it', label: 'Italiano', flag: '🇮🇹' },
  { code: 'fr', label: 'Français', flag: '🇫🇷' },
  { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { code: 'pt', label: 'Português', flag: '🇵🇹' },
  { code: 'zh-hans', label: '简体中文', flag: '🇨🇳' },
  { code: 'zh-hant', label: '繁體中文', flag: '🇭🇰' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
];

const baseSettings = {
  settings: "Settings", theme: "Theme", light: "Light", dark: "Dark", system: "System",
  rate_app: "Rate App", share_app: "Share App", app_version: "Version"
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    ...baseSettings,
    levels: "Levels", daily: "Daily", streak: "Streak", level: "Level", completed: "Completed",
    daily_puzzle: "Daily Puzzle", well_done: "Well Done!", amazing: "Amazing!", home: "Home",
    next: "Next", back_to_menu: "Back", share_score: "Share Score", loading: "Loading...",
    great: "Great!", challenge: "Challenge", pack: "Pack", solve_to_maintain: "Solve to maintain your streak!",
    come_back_tomorrow: "You've finished today's puzzle. Come back tomorrow!", language: "Language",
    show_solution: "Show Solution", hide_solution: "Hide Solution", error_load: "Error loading level.",
    shop: "Shop", themes: "Themes", hints: "Hints", buy: "Buy", owned: "Owned",
    not_enough_stars: "Not enough stars!", upcoming: "Coming Soon", watch_ad: "Watch Ad",
    free_hints: "Free Hints", remove_ads: "Remove Ads", unlock_all: "Unlock All Levels",
    restore_purchases: "Restore Purchases", upgrades: "Upgrades", back: "Back", retry: "Retry",
    hint_next: "Next Step", hint_path: "Short Path", hint_reveal: "Reveal All", not_enough_hints: "Not enough hints!",
    full_game: "Unlock Full Game", full_game_desc: "No Ads, All Levels, 500 Stars & 100 Hints", best_value: "Best Value",
    close: "Close"
  },
  da: {
    settings: "Indstillinger", theme: "Tema", light: "Lys", dark: "Mørk", system: "System",
    rate_app: "Bedøm app", share_app: "Del app", app_version: "Version",
    levels: "Baner", daily: "Daglig", streak: "Streak", level: "Bane", completed: "Gennemført",
    daily_puzzle: "Dagens Opgave", well_done: "Flot klaret!", amazing: "Fantastisk!", home: "Hjem",
    next: "Næste", back_to_menu: "Tilbage", share_score: "Del resultat", loading: "Henter...",
    great: "Super!", challenge: "Udfordring", pack: "Pakke", solve_to_maintain: "Løs for at beholde din streak!",
    come_back_tomorrow: "Du er færdig for i dag. Kom tilbage i morgen!", language: "Sprog",
    show_solution: "Vis løsning", hide_solution: "Skjul løsning", error_load: "Kunne ikke hente bane.",
    shop: "Butik", themes: "Temaer", hints: "Hints", buy: "Køb", owned: "Ejet",
    not_enough_stars: "Ikke nok stjerner!", upcoming: "Kommer snart", watch_ad: "Se Reklame",
    free_hints: "Gratis Hints", remove_ads: "Fjern Reklamer", unlock_all: "Lås alt op",
    restore_purchases: "Gendan Køb", upgrades: "Opgraderinger", back: "Tilbage", retry: "Prøv igen",
    hint_next: "Næste felt", hint_path: "Kort sti", hint_reveal: "Vis hele løsningen", not_enough_hints: "Ikke nok hints!",
    full_game: "Køb Fulde Spil", full_game_desc: "Ingen reklamer, alle baner, 500 stjerner & 100 hints", best_value: "Bedste køb",
    close: "Luk"
  },
  sv: { settings: "Inställningar", theme: "Tema", light: "Ljus", dark: "Mörk", system: "System", levels: "Nivåer", daily: "Daglig", streak: "Svit", level: "Nivå", completed: "Slutförd", daily_puzzle: "Dagens pussel", well_done: "Bra gjort!", amazing: "Fantastiskt!", home: "Hem", next: "Nästa", back_to_menu: "Tillbaka", share_score: "Dela poäng", loading: "Laddar...", great: "Bra!", challenge: "Utmaning", pack: "Paket", solve_to_maintain: "Lös för att behålla din svit!", come_back_tomorrow: "Du är klar för idag. Kom tillbaka imorgon!", language: "Språk", show_solution: "Visa lösning", hide_solution: "Dölj lösning", error_load: "Kunde inte ladda nivå.", shop: "Butik", themes: "Teman", hints: "Tips", buy: "Köp", owned: "Ägd", not_enough_stars: "Inte tillräckligt med stjärnor!", upcoming: "Kommer snart", watch_ad: "Se reklam", free_hints: "Gratis tips", remove_ads: "Ta bort reklam", unlock_all: "Lås upp alla nivåer", restore_purchases: "Återställ köp", upgrades: "Uppgraderingar", back: "Tillbaka", retry: "Försök igen", hint_next: "Nästa steg", hint_path: "Kort väg", hint_reveal: "Visa allt", not_enough_hints: "Inte tillräckligt med tips!", full_game: "Lås upp hela spelet", full_game_desc: "Ingen reklam, alla nivåer, 500 stjärnor & 100 tips", best_value: "Prisvärt", close: "Stäng" },
  no: { settings: "Innstillinger", theme: "Tema", light: "Lys", dark: "Mørk", system: "System", levels: "Nivåer", daily: "Daglig", streak: "Rekke", level: "Nivå", completed: "Fullført", daily_puzzle: "Dagens puslespill", well_done: "Bra gjort!", amazing: "Fantastisk!", home: "Hjem", next: "Neste", back_to_menu: "Tilbake", share_score: "Del poeng", loading: "Laster...", great: "Supert!", challenge: "Utfordring", pack: "Pakke", solve_to_maintain: "Løs for å beholde rekken!", come_back_tomorrow: "Du er ferdig for i dag. Kom tilbage i morgen!", language: "Språk", show_solution: "Vis løsning", hide_solution: "Skjul løsning", error_load: "Kunne ikke laste nivå.", shop: "Butikk", themes: "Temaer", hints: "Hint", buy: "Kjøb", owned: "Eier", not_enough_stars: "Ikke nok stjerner!", upcoming: "Kommer snart", watch_ad: "Se reklame", free_hints: "Gratis hint", remove_ads: "Fjern reklame", unlock_all: "Lås opp alle nivåer", restore_purchases: "Gjenopprett kjøp", upgrades: "Opgraderinger", back: "Tilbake", retry: "Prøv igen", hint_next: "Neste steg", hint_path: "Kort sti", hint_reveal: "Vis alt", not_enough_hints: "Ikke nok hint!", full_game: "Lås opp hele spillet", full_game_desc: "Ingen reklame, alle nivåer, 500 stjerner & 100 hint", best_value: "Beste verdi", close: "Lukk" },
  fi: { settings: "Asetukset", theme: "Teema", light: "Vaalea", dark: "Tumma", system: "Järjestelmä", levels: "Tasot", daily: "Päivittäinen", streak: "Putki", level: "Taso", completed: "Valmis", daily_puzzle: "Päivän pähkinä", well_done: "Hyvin tehty!", amazing: "Mahtavaa!", home: "Koti", next: "Seuraava", back_to_menu: "Takaisin", share_score: "Jaa tulos", loading: "Ladataan...", great: "Hienoa!", challenge: "Haaste", pack: "Pakkaus", solve_to_maintain: "Ratkaise pitääksesi putkesi!", come_back_tomorrow: "Olet valmis tältä päivältä. Palaa huomeanna!", language: "Kieli", show_solution: "Näytä ratkaisu", hide_solution: "Piilota ratkaisu", error_load: "Virhe ladattaessa tasoa.", shop: "Kauppa", themes: "Teemat", hints: "Vinkit", buy: "Osta", owned: "Omistettu", not_enough_stars: "Ei tarpeeksi tähtiä!", upcoming: "Tulossa pian", watch_ad: "Katso mainos", free_hints: "Ilmaiset vinkit", remove_ads: "Poista mainokset", unlock_all: "Avaa kaikki tasot", restore_purchases: "Palauta ostokset", upgrades: "Päivitykset", back: "Takaisin", retry: "Yritä uudelleen", hint_next: "Seuraava vaihe", hint_path: "Lyhyt reitti", hint_reveal: "Paljasta kaikki", not_enough_hints: "Ei tarpeeksi vinkkejä!", full_game: "Avaa koko peli", full_game_desc: "Ei mainoksia, kaikki tasot, 500 tähteä & 100 vinkkiä", best_value: "Paras arvo", close: "Sulje" },
  es: { settings: "Ajustes", theme: "Tema", light: "Claro", dark: "Oscuro", system: "Sistema", levels: "Niveles", daily: "Diario", streak: "Racha", level: "Nivel", completed: "Completado", daily_puzzle: "Puzle diario", well_done: "¡Bien hecho!", amazing: "¡Increíble!", home: "Inicio", next: "Siguiente", back_to_menu: "Atrás", share_score: "Compartir", loading: "Cargando...", great: "¡Genial!", challenge: "Desafío", pack: "Paquete", solve_to_maintain: "¡Resuelve para mantener tu racha!", come_back_tomorrow: "Has terminado por hoy. ¡Vuelve mañana!", language: "Idioma", show_solution: "Ver solución", hide_solution: "Ocultar solución", error_load: "Error al cargar nivel.", shop: "Tienda", themes: "Temas", hints: "Pistas", buy: "Comprar", owned: "Obtenido", not_enough_stars: "¡No hay suficientes estrellas!", upcoming: "Próximamente", watch_ad: "Ver anuncio", free_hints: "Pistas gratis", remove_ads: "Quitar anuncios", unlock_all: "Desbloquear todo", restore_purchases: "Restaurar compras", upgrades: "Mejoras", back: "Atrás", retry: "Reintentar", hint_next: "Siguiente paso", hint_path: "Camino corto", hint_reveal: "Revelar todo", not_enough_hints: "¡No hay suficientes pistas!", full_game: "Desbloquear juego completo", full_game_desc: "Sin anuncios, todos los niveles, 500 estrellas y 100 pistas", best_value: "Mejor precio", close: "Cerrar" },
  it: { settings: "Impostazioni", theme: "Tema", light: "Chiaro", dark: "Scuro", system: "Sistema", levels: "Livelli", daily: "Giornaliero", streak: "Serie", level: "Livello", completed: "Completato", daily_puzzle: "Puzzle del giorno", well_done: "Ben fatto!", amazing: "Incredibile!", home: "Home", next: "Avanti", back_to_menu: "Indietro", share_score: "Condividi", loading: "Caricamento...", great: "Ottimo!", challenge: "Sfida", pack: "Pacchetto", solve_to_maintain: "Risolvi per mantenere la serie!", come_back_tomorrow: "Hai finito per oggi. Torna domani!", language: "Lingua", show_solution: "Mostra soluzione", hide_solution: "Nascondi soluzione", error_load: "Errore caricamento livello.", shop: "Negozio", themes: "Temi", hints: "Suggerimenti", buy: "Acquista", owned: "Posseduto", not_enough_stars: "Stelle insufficienti!", upcoming: "In arrivo", watch_ad: "Guarda annuncio", free_hints: "Suggerimenti gratuiti", remove_ads: "Rimuovi pubblicità", unlock_all: "Sblocca tutto", restore_purchases: "Ripristina acquisti", upgrades: "Potenziamenti", back: "Indietro", retry: "Riprova", hint_next: "Prossimo passo", hint_path: "Percorso breve", hint_reveal: "Rileva tutto", not_enough_hints: "Suggerimenti insufficienti!", full_game: "Sblocca gioco completo", full_game_desc: "Senza pubblicità, tutti i livelli, 500 stelle e 100 suggerimenti", best_value: "Migliore offerta", close: "Chiudi" },
  fr: { settings: "Réglages", theme: "Thème", light: "Clair", dark: "Sombre", system: "Système", levels: "Niveaux", daily: "Quotidien", streak: "Série", level: "Niveau", completed: "Terminé", daily_puzzle: "Puzzle du jour", well_done: "Bien joué !", amazing: "Incroyable !", home: "Accueil", next: "Suivant", back_to_menu: "Retour", share_score: "Partager", loading: "Chargement...", great: "Super !", challenge: "Défi", pack: "Pack", solve_to_maintain: "Résolvez pour garder votre série !", come_back_tomorrow: "C'est fini pour aujourd'hui. À demain !", language: "Langue", show_solution: "Voir solution", hide_solution: "Cacher solution", error_load: "Erreur de chargement.", shop: "Boutique", themes: "Thèmes", hints: "Indices", buy: "Acheter", owned: "Possédé", not_enough_stars: "Pas assez d'étoiles !", upcoming: "À venir", watch_ad: "Voir pub", free_hints: "Indices gratuits", remove_ads: "Enlever les pubs", unlock_all: "Tout débloquer", restore_purchases: "Restaurer les achats", upgrades: "Améliorations", back: "Retour", retry: "Réessayer", hint_next: "Étape suivante", hint_path: "Chemin court", hint_reveal: "Tout révéler", not_enough_hints: "Pas assez d'indices !", full_game: "Débloquer le jeu complet", full_game_desc: "Sans pub, tous les niveaux, 500 étoiles et 100 indices", best_value: "Meilleure offre", close: "Fermer" },
  de: { settings: "Einstellungen", theme: "Thema", light: "Hell", dark: "Dunkel", system: "System", level: "Level", completed: "Abgeschlossen", daily_puzzle: "Tagesrätsel", well_done: "Gut gemacht!", amazing: "Unglaublich!", home: "Home", next: "Weiter", back_to_menu: "Zurück", share_score: "Teilen", loading: "Laden...", great: "Super!", challenge: "Herausforderung", pack: "Paket", solve_to_maintain: "Löse es, um deine Serie zu halten!", come_back_tomorrow: "Fertig für heute. Bis morgen!", language: "Sprache", show_solution: "Lösung zeigen", hide_solution: "Lösung verbergen", error_load: "Fehler beim Laden.", shop: "Shop", themes: "Themen", hints: "Hinweise", buy: "Kaufen", owned: "Besitz", not_enough_stars: "Nicht genug Sterne!", upcoming: "Demnächst", watch_ad: "Video ansehen", free_hints: "Gratis Hinweise", remove_ads: "Werbung entfernen", unlock_all: "Alles freischalten", restore_purchases: "Käufe wiederherstellen", upgrades: "Upgrades", back: "Zurück", retry: "Wiederholen", hint_next: "Nächster Schritt", hint_path: "Kurzer Pfad", hint_reveal: "Alles zeigen", not_enough_hints: "Nicht genug Hinweise!", full_game: "Vollversion freischalten", full_game_desc: "Keine Werbung, alle Level, 500 Sterne & 100 Hinweise", best_value: "Bester Preis", close: "Schließen" },
  pt: { settings: "Configurações", theme: "Tema", light: "Claro", dark: "Escuro", system: "Sistema", levels: "Níveis", daily: "Diário", streak: "Sequência", level: "Nível", completed: "Concluído", daily_puzzle: "Puzzle diário", well_done: "Bem feito!", amazing: "Incrível!", home: "Início", next: "Próximo", back_to_menu: "Voltar", share_score: "Partilhar", loading: "A carregar...", great: "Ótimo!", challenge: "Desafio", pack: "Pacote", solve_to_maintain: "Resolve para manter a sequência!", come_back_tomorrow: "Terminaste por hoje. Volta amanhã!", language: "Idioma", show_solution: "Ver soluzione", hide_solution: "Ocultar soluzione", error_load: "Erro ao carregar nivel.", shop: "Loja", themes: "Temas", hints: "Dicas", buy: "Comprar", owned: "Adquirido", not_enough_stars: "Estrelas insuficientes!", upcoming: "Em breve", watch_ad: "Ver anúncio", free_hints: "Dicas grátis", remove_ads: "Remover anúncios", unlock_all: "Desbloquear tutto", restore_purchases: "Restaurar compras", upgrades: "Upgrades", back: "Voltar", retry: "Repetir", hint_next: "Próximo passo", hint_path: "Caminho curto", hint_reveal: "Revelar tudo", not_enough_hints: "Dicas insuficientes!", full_game: "Desbloquear jogo completo", full_game_desc: "Sem anúncios, todos os níveis, 500 estrelas e 100 dicas", best_value: "Melhor valor", close: "Fechar" },
  "zh-hans": { settings: "设置", theme: "主题", light: "明亮", dark: "深色", system: "跟随系统", levels: "关卡", daily: "每日", streak: "连胜", level: "关卡", completed: "已完成", daily_puzzle: "每日谜题", well_done: "做得好！", amazing: "太棒了！", home: "主页", next: "下一关", back_to_menu: "返回", share_score: "分享得分", loading: "加载中...", great: "好极了！", challenge: "挑战", pack: "关卡包", solve_to_maintain: "完成以保持连胜！", come_back_tomorrow: "今天已完成。明天再来！", language: "语言", show_solution: "显示答案", hide_solution: "隐藏答案", error_load: "加载关卡时出错。", shop: "商店", themes: "主题", hints: "提示", buy: "购买", owned: "已拥有", not_enough_stars: "星星不足！", upcoming: "即将推出", watch_ad: "看广告", free_hints: "免费提示", remove_ads: "去广告", unlock_all: "解锁全部关卡", restore_purchases: "恢复购买", upgrades: "升级", back: "返回", retry: "重试", hint_next: "下一步", hint_path: "短路径", hint_reveal: "揭晓全部", not_enough_hints: "提示不足！", full_game: "解锁完整版", full_game_desc: "无广告，解锁所有关卡，赠送 500 星星和 100 提示", best_value: "最超值", close: "关闭" },
  "zh-hant": { settings: "設置", theme: "主題", light: "明亮", dark: "深色", system: "跟隨系統", levels: "關卡", daily: "每日", streak: "連勝", level: "關卡", completed: "已完成", daily_puzzle: "每日謎題", well_done: "做得好！", amazing: "太棒了！", home: "主頁", next: "下一關", back_to_menu: "返回", share_score: "分享得分", loading: "加載中...", great: "好極了！", challenge: "挑戰", pack: "關卡包", solve_to_maintain: "完成以保持連勝！", come_back_tomorrow: "今天已完成。明天再來！", language: "語言", show_solution: "顯示答案", hide_solution: "隱藏答案", error_load: "加載關卡時出錯。", shop: "商店", themes: "主題", hints: "提示", buy: "購買", owned: "已擁有", not_enough_stars: "星星不足！", upcoming: "即將推出", watch_ad: "看廣告", free_hints: "免費提示", remove_ads: "去廣告", unlock_all: "解鎖全部關卡", restore_purchases: "恢復購買", upgrades: "升級", back: "返回", retry: "重試", hint_next: "下一步", hint_path: "短路徑", hint_reveal: "揭曉全部", not_enough_hints: "提示不足！", full_game: "解鎖完整版", full_game_desc: "無廣告，解鎖所有關卡，贈送 500 星星和 100 提示", best_value: "最超值", close: "關閉" },
  ja: { settings: "設定", theme: "テーマ", light: "ライト", dark: "ダーク", system: "システム設定", levels: "レベル", daily: "デイリー", streak: "記録", level: "レベル", completed: "完了", daily_puzzle: "今日のパズル", well_done: "お見事！", amazing: "素晴らしい！", home: "ホーム", next: "次へ", back_to_menu: "戻る", share_score: "スコアを共有", loading: "読み込み中...", great: "すごい！", challenge: "チャレンジ", pack: "パック", solve_to_maintain: "記録を維持するために解こう！", come_back_tomorrow: "今日は終了です。また明日！", language: "言語", show_solution: "ヒントを見る", hide_solution: "ヒントを隠す", error_load: "レベルの読み込みに失敗しました。", shop: "ショップ", themes: "テーマ", hints: "ヒント", buy: "購入", owned: "所持済み", not_enough_stars: "スターが足りません！", upcoming: "近日公開", watch_ad: "広告を見る", free_hints: "無料ヒント", remove_ads: "広告なし", unlock_all: "全レベル解放", restore_purchases: "購入の復元", upgrades: "アップグレード", back: "戻る", retry: "やり直し", hint_next: "次のステップ", hint_path: "短いヒント", hint_reveal: "全表示", not_enough_hints: "ヒントが足りません！", full_game: "フルゲームを解放", full_game_desc: "広告なし、全レベル解放、500スター＆100ヒント付き", best_value: "お得", close: "閉じる" },
  ko: { settings: "설정", theme: "테마", light: "라이트", dark: "다크", system: "시스템 설정", levels: "레벨", daily: "일일", streak: "연속", level: "레벨", completed: "완료", daily_puzzle: "오늘의 퍼즐", well_done: "잘했어요!", amazing: "놀라워요!", home: "홈", next: "다음", back_to_menu: "뒤로", share_score: "점수 공유", loading: "로딩 중...", great: "좋아요!", challenge: "챌린지", pack: "팩", solve_to_maintain: "연속 기록을 유지하려면 푸세요!", come_back_tomorrow: "오늘 분량 완료! 내일 만나요.", language: "언어", show_solution: "정답 보기", hide_solution: "정답 숨기기", error_load: "레벨 로딩 오류.", shop: "상점", themes: "테마", hints: "힌트", buy: "구매", owned: "보유함", not_enough_stars: "별이 부족합니다!", upcoming: "곧 출시", watch_ad: "광고 시청", free_hints: "무료 힌트", remove_ads: "광고 제거", unlock_all: "모든 레벨 해제", restore_purchases: "구매 복원", upgrades: "업그레이드", back: "뒤로", retry: "다시 시도", hint_next: "다음 단계", hint_path: "부분 정답", hint_reveal: "전체 정답", not_enough_hints: "힌트가 부족합니다!", full_game: "풀 버전 해제", full_game_desc: "광고 없음, 모든 레벨 해제, 500 스타 & 100 힌트 제공", best_value: "최고의 가치", close: "닫기" }
};
